---
name: data-visualization-demo
channels:
  - defaults
  - jkglasbrenner
dependencies:
  - anaconda=5.3.0=py37_0
  - autopep8=1.4
  - nodejs
  - pyhamcrest=1.9.0
  - pytest-runner
  - sphinx_rtd_theme
  - yapf=0.23.0
  - pip:
      - pip==18.0
      - plotly
      - pydocstyle
...
